server:
  port: ${PORT:8082}
  servlet:
    context-path: /api

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql:${DATABASE_NAME://localhost:5432/AtomHack}
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:123}
  jpa:
    openInView: true
    show-sql: false
    generateDdl: true
    database: postgresql
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  main:
    allow-circular-references: true
minio:
  endpoint: ${MINIO_ENDPOINT:http://31.129.109.44:9000}
  accessKey: ${MINIO_ACCESS_KEY:miniominio}
  secretKey: ${MINIO_SECRET_KEY:miniominio}
  bucket: ${MINIO_BUCKET:aquarion}
init: ${MINIO_BUCKET:true}
serverName: ${SERVER_NAME:aquarion}
